[2025-07-03T09:12:27.762+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-03T09:12:27.780+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: init_minio_structure.create_bucket manual__2025-07-03T09:12:25.635769+00:00 [queued]>
[2025-07-03T09:12:27.785+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: init_minio_structure.create_bucket manual__2025-07-03T09:12:25.635769+00:00 [queued]>
[2025-07-03T09:12:27.786+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-07-03T09:12:27.795+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): create_bucket> on 2025-07-03 09:12:25.635769+00:00
[2025-07-03T09:12:27.800+0000] {standard_task_runner.py:63} INFO - Started process 61 to run task
[2025-07-03T09:12:27.802+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'init_minio_structure', 'create_bucket', 'manual__2025-07-03T09:12:25.635769+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/init_minio_structure.py', '--cfg-path', '/tmp/tmp88yp00p0']
[2025-07-03T09:12:27.804+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask create_bucket
[2025-07-03T09:12:27.849+0000] {task_command.py:426} INFO - Running <TaskInstance: init_minio_structure.create_bucket manual__2025-07-03T09:12:25.635769+00:00 [running]> on host fa1a308ca64a
[2025-07-03T09:12:27.916+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='init_minio_structure' AIRFLOW_CTX_TASK_ID='create_bucket' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T09:12:25.635769+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-03T09:12:25.635769+00:00'
[2025-07-03T09:12:27.917+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-03T09:12:27.937+0000] {logging_mixin.py:188} INFO - ðŸ›  DÃ©marrage de create_bucket_if_missing()
[2025-07-03T09:12:28.038+0000] {logging_mixin.py:188} INFO - ðŸ“¡ Tentative connexion MinIO Ã  : http://sport-minio:9000
[2025-07-03T09:12:28.040+0000] {logging_mixin.py:188} INFO - ðŸ§¨ Bucket inexistant, tentative de crÃ©ation : Unable to locate credentials
[2025-07-03T09:12:28.042+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-03T09:12:28.042+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/init_minio_structure.py", line 33, in create_bucket_if_missing
    helper.client.head_bucket(Bucket=BUCKET)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 989, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 1015, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/signers.py", line 195, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/init_minio_structure.py", line 37, in create_bucket_if_missing
    helper.client.create_bucket(Bucket=BUCKET)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 989, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 1015, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/signers.py", line 195, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2025-07-03T09:12:28.056+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=init_minio_structure, task_id=create_bucket, execution_date=20250703T091225, start_date=20250703T091227, end_date=20250703T091228
[2025-07-03T09:12:28.063+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task create_bucket (Unable to locate credentials; 61)
[2025-07-03T09:12:28.095+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-03T09:12:28.111+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-03T09:12:28.113+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
