2025-07-02 11:16:43.055 | ERROR    | __main__:main:107 - Erreur PostgreSQL : connection to server at "localhost" (::1), port 5432 failed: fe_sendauth: no password supplied

Traceback (most recent call last):

  File "F:\1.Boulot\03_Github\sport-data-solution\airflow\scripts\import_employes.py", line 119, in <module>
    main()
    └ <function main at 0x0000028FA24B9E40>

> File "F:\1.Boulot\03_Github\sport-data-solution\airflow\scripts\import_employes.py", line 66, in main
    conn = psycopg2.connect(
           │        └ <function connect at 0x0000028FA21DC360>
           └ <module 'psycopg2' from 'C:\\Users\\rouss\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\psycopg2\\__init_...

  File "C:\Users\rouss\AppData\Local\Programs\Python\Python311\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           │        │                       │                     └ {}
           │        │                       └ None
           │        └ ''
           └ <built-in function _connect>

psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: fe_sendauth: no password supplied

2025-07-02 11:34:55.381 | DEBUG    | __main__:<module>:42 - Connexion à PostgreSQL : host=None db=None user=None
2025-07-02 11:34:55.515 | INFO     | __main__:main:77 - 📄 Chargement de 161 employés depuis le fichier Excel
2025-07-02 11:34:55.515 | INFO     | __main__:main:80 - Connexion à la base PostgreSQL...
2025-07-02 11:34:55.521 | ERROR    | __main__:main:128 - ❌ Erreur lors de l'import : connection to server at "localhost" (::1), port 5432 failed: fe_sendauth: no password supplied

Traceback (most recent call last):

  File "F:\1.Boulot\03_Github\sport-data-solution\airflow\scripts\import_employes.py", line 145, in <module>
    main()
    └ <function main at 0x0000019F7FD39EE0>

> File "F:\1.Boulot\03_Github\sport-data-solution\airflow\scripts\import_employes.py", line 81, in main
    conn = psycopg2.connect(
           │        └ <function connect at 0x0000019F7FA60400>
           └ <module 'psycopg2' from 'C:\\Users\\rouss\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\psycopg2\\__init_...

  File "C:\Users\rouss\AppData\Local\Programs\Python\Python311\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           │        │                       │                     └ {}
           │        │                       └ None
           │        └ ''
           └ <built-in function _connect>

psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: fe_sendauth: no password supplied

2025-07-02 11:34:55.521 | INFO     | __main__:main:137 - 🔌 Connexion PostgreSQL fermée.
2025-07-02 11:40:38.632 | INFO     | __main__:<module>:46 - 🔍 Connexion vers PostgreSQL : user@sport-postgres:5432/sportdata
2025-07-02 11:40:38.766 | INFO     | __main__:main:80 - 📄 Chargement de 161 employés depuis le fichier Excel
2025-07-02 11:40:38.771 | INFO     | __main__:main:83 - Connexion à la base PostgreSQL...
2025-07-02 11:40:41.477 | ERROR    | __main__:main:131 - ❌ Erreur lors de l'import : 
Traceback (most recent call last):

  File "F:\1.Boulot\03_Github\sport-data-solution\airflow\scripts\import_employes.py", line 147, in <module>
    main()
    └ <function main at 0x0000026CB9939EE0>

> File "F:\1.Boulot\03_Github\sport-data-solution\airflow\scripts\import_employes.py", line 84, in main
    conn = psycopg2.connect(
           │        └ <function connect at 0x0000026CE48CC400>
           └ <module 'psycopg2' from 'C:\\Users\\rouss\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\psycopg2\\__init_...

  File "C:\Users\rouss\AppData\Local\Programs\Python\Python311\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           │        │                       │                     └ {}
           │        │                       └ None
           │        └ 'host=sport-postgres port=5432 dbname=sportdata user=user password=password'
           └ <built-in function _connect>

psycopg2.OperationalError
2025-07-02 11:40:41.477 | INFO     | __main__:main:139 - 🔌 Connexion PostgreSQL fermée.
2025-07-02 10:14:49.343 | INFO     | __main__:<module>:44 - 🔍 Connexion à PostgreSQL → user@sport-postgres:5432/sportdata
2025-07-02 10:14:49.553 | INFO     | __main__:main:81 - 📄 Chargement de 161 employés depuis le fichier Excel
2025-07-02 10:14:49.558 | SUCCESS  | __main__:main:89 - ✅ Connexion PostgreSQL réussie
2025-07-02 10:14:49.559 | INFO     | __main__:main:92 - 🧱 Création de la table employes (DROP + CREATE)
2025-07-02 10:14:49.567 | INFO     | __main__:main:112 - 📥 Insertion des employés en base...
2025-07-02 10:14:49.608 | SUCCESS  | __main__:main:125 - 🎯 Insertion terminée avec succès.
2025-07-02 10:14:49.609 | INFO     | __main__:main:136 - 🔌 Connexion PostgreSQL fermée.
